language: go

go:
  - tip

before_install:
  - go get -t -v ./...

before_script:
  - curl https://get.dgraph.io > /tmp/get.sh
  - chmod +x /tmp/get.sh
  - /tmp/get.sh -y
  - dgraph zero &
  - dgraph alpha --zero localhost:5080 --badger.compression=none --cache_mb 0 &
  - sleep 22

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
