language: go

go:
  - master
  - tip

before_install:
  - go get -t -v github.com/ppp225/ndgo

before_script:
  - curl https://get.dgraph.io -sSf | bash
  - dgraph zero &
  - dgraph alpha --lru_mb 1024 --zero localhost:5080 &

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
